# Generated by Django 5.2.4 on 2025-07-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_deleted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='deleted_by',
        ),
    ]
