# Generated by Django 5.2.4 on 2025-07-31 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_conversation_deleted_by'),
        ('users', '0005_userprofile_bio_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_conversations', to='users.userprofile'),
        ),
    ]
