# Generated by Django 5.2.4 on 2025-07-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deletion_timestamps',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
