# Generated by Django 5.2.5 on 2025-08-15 05:49

from django.db import migrations

def fix_empty_emails(apps, schema_editor):
    """Set empty email strings to NULL to avoid constraint issues"""
    User = apps.get_model('auth', 'User')
    empty_email_users = User.objects.filter(email='')
    empty_email_users.update(email=None)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_is_online_userprofile_last_seen'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(
            fix_empty_emails,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunSQL(
            "CREATE UNIQUE INDEX unique_user_email ON auth_user (email) WHERE email IS NOT NULL AND email != '';",
            reverse_sql="DROP INDEX IF EXISTS unique_user_email;"
        ),
    ]
