name: CI/CD Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Copy project to EC2 (exclude heavy/unneeded files)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: |
            backend/**
            frontend/**
            docker-compose.yml
          target: "~/app"
          overwrite: true
          strip_components: 0
          rm: false
          exclude: |
            **/.git/**
            **/.github/**
            **/node_modules/**
            backend/media/**
            backend/staticfiles/**

      - name: Deploy with Docker Compose on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd ~/app
            # Ensure env file exists on server (not uploaded via git)
            if [ ! -f backend/.env.production ]; then
              echo "ERROR: backend/.env.production not found on server" >&2
              exit 1
            fi
            docker-compose down
            docker-compose up -d --build
            docker-compose ps
